/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export type ProjectStatus = { PLANNING: null } | { ACTIVE: null } | { ON_HOLD: null } | { COMPLETED: null } | { CANCELLED: null };
export type Priority = { LOW: null } | { MEDIUM: null } | { HIGH: null } | { URGENT: null };
export type TaskStatus = { TODO: null } | { IN_PROGRESS: null } | { IN_REVIEW: null } | { DONE: null };
export type NotifType = { TASK_ASSIGNED: null } | { TASK_UPDATED: null } | { DOC_UPDATED: null } | { PROJECT_UPDATED: null };
export type EntityType = { TASK: null } | { DOCUMENT: null };
export type UserRole = { ADMIN: null } | { MANAGER: null } | { EMPLOYEE: null };

export interface Project {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
  priority: Priority;
  ownerId: Principal;
  memberIds: Principal[];
  createdAt: bigint;
  updatedAt: bigint;
  dueDate: [] | [bigint];
}

export interface SubProject {
  id: string;
  parentProjectId: string;
  name: string;
  description: string;
  category: string;
  status: ProjectStatus;
  priority: Priority;
  ownerId: Principal;
  memberIds: Principal[];
  createdAt: bigint;
  updatedAt: bigint;
  dueDate: [] | [bigint];
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: Priority;
  assigneeId: [] | [Principal];
  reporterId: Principal;
  createdAt: bigint;
  updatedAt: bigint;
  dueDate: [] | [bigint];
  tags: string[];
}

export interface Document {
  id: string;
  projectId: string;
  title: string;
  content: string;
  authorId: Principal;
  createdAt: bigint;
  updatedAt: bigint;
  version: bigint;
  fileUrl: [] | [string];
}

export interface Notification {
  id: string;
  userId: Principal;
  message: string;
  notifType: NotifType;
  relatedId: string;
  isRead: boolean;
  createdAt: bigint;
}

export interface Comment {
  id: string;
  entityId: string;
  entityType: EntityType;
  authorId: Principal;
  content: string;
  createdAt: bigint;
}

export interface Activity {
  id: string;
  actorId: Principal;
  action: string;
  entityType: string;
  entityId: string;
  timestamp: bigint;
}

export interface DashboardStats {
  totalProjects: bigint;
  totalTasks: bigint;
  todoCount: bigint;
  inProgressCount: bigint;
  inReviewCount: bigint;
  doneCount: bigint;
  recentActivities: Activity[];
}

export interface UserProfile {
  id: Principal;
  name: string;
  role: string;
  department: string;
  email: string;
  phone: string;
  userRole: UserRole;
  createdAt: bigint;
  updatedAt: bigint;
}

export interface backendInterface {
  _initializeAccessControlWithSecret(secret: string): Promise<void>;
  createProject(name: string, description: string, status: ProjectStatus, priority: Priority, dueDate: [] | [bigint]): Promise<Project>;
  getProjects(): Promise<Project[]>;
  getProject(id: string): Promise<[] | [Project]>;
  updateProject(id: string, name: string, description: string, status: ProjectStatus, priority: Priority, dueDate: [] | [bigint], memberIds: Principal[]): Promise<[] | [Project]>;
  deleteProject(id: string): Promise<boolean>;
  createSubProject(parentProjectId: string, name: string, description: string, category: string, status: ProjectStatus, priority: Priority, dueDate: [] | [bigint]): Promise<SubProject>;
  getSubProjects(): Promise<SubProject[]>;
  getSubProjectsByParent(parentProjectId: string): Promise<SubProject[]>;
  getSubProject(id: string): Promise<[] | [SubProject]>;
  updateSubProject(id: string, name: string, description: string, category: string, status: ProjectStatus, priority: Priority, dueDate: [] | [bigint], memberIds: Principal[]): Promise<[] | [SubProject]>;
  deleteSubProject(id: string): Promise<boolean>;
  createTask(projectId: string, title: string, description: string, status: TaskStatus, priority: Priority, assigneeId: [] | [Principal], dueDate: [] | [bigint], tags: string[]): Promise<Task>;
  getTasks(): Promise<Task[]>;
  getTasksByProject(projectId: string): Promise<Task[]>;
  getTask(id: string): Promise<[] | [Task]>;
  updateTask(id: string, title: string, description: string, status: TaskStatus, priority: Priority, assigneeId: [] | [Principal], dueDate: [] | [bigint], tags: string[]): Promise<[] | [Task]>;
  deleteTask(id: string): Promise<boolean>;
  createDocument(projectId: string, title: string, content: string, fileUrl: [] | [string]): Promise<Document>;
  getDocuments(): Promise<Document[]>;
  getDocumentsByProject(projectId: string): Promise<Document[]>;
  getDocument(id: string): Promise<[] | [Document]>;
  updateDocument(id: string, title: string, content: string, fileUrl: [] | [string]): Promise<[] | [Document]>;
  deleteDocument(id: string): Promise<boolean>;
  getMyNotifications(): Promise<Notification[]>;
  markNotificationRead(id: string): Promise<boolean>;
  markAllNotificationsRead(): Promise<bigint>;
  addComment(entityId: string, entityType: EntityType, content: string): Promise<Comment>;
  getComments(entityId: string): Promise<Comment[]>;
  deleteComment(id: string): Promise<boolean>;
  getRecentActivity(limit: bigint): Promise<Activity[]>;
  getDashboardStats(): Promise<DashboardStats>;
  registerProfile(name: string, role: string, department: string, email: string, phone: string, userRole: UserRole): Promise<UserProfile>;
  getMyProfile(): Promise<[] | [UserProfile]>;
  getAllProfiles(): Promise<UserProfile[]>;
  getProfile(principal: Principal): Promise<[] | [UserProfile]>;
  updateProfile(name: string, role: string, department: string, email: string, phone: string, userRole: UserRole): Promise<[] | [UserProfile]>;
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    _initializeAccessControlWithSecret(secret: string): Promise<void> { return (this.actor as any)._initializeAccessControlWithSecret(secret); }
    createProject(...args: any[]): Promise<any> { return (this.actor as any).createProject(...args); }
    getProjects(): Promise<any> { return (this.actor as any).getProjects(); }
    getProject(id: string): Promise<any> { return (this.actor as any).getProject(id); }
    updateProject(...args: any[]): Promise<any> { return (this.actor as any).updateProject(...args); }
    deleteProject(id: string): Promise<any> { return (this.actor as any).deleteProject(id); }
    createSubProject(...args: any[]): Promise<any> { return (this.actor as any).createSubProject(...args); }
    getSubProjects(): Promise<any> { return (this.actor as any).getSubProjects(); }
    getSubProjectsByParent(parentProjectId: string): Promise<any> { return (this.actor as any).getSubProjectsByParent(parentProjectId); }
    getSubProject(id: string): Promise<any> { return (this.actor as any).getSubProject(id); }
    updateSubProject(...args: any[]): Promise<any> { return (this.actor as any).updateSubProject(...args); }
    deleteSubProject(id: string): Promise<any> { return (this.actor as any).deleteSubProject(id); }
    createTask(...args: any[]): Promise<any> { return (this.actor as any).createTask(...args); }
    getTasks(): Promise<any> { return (this.actor as any).getTasks(); }
    getTasksByProject(projectId: string): Promise<any> { return (this.actor as any).getTasksByProject(projectId); }
    getTask(id: string): Promise<any> { return (this.actor as any).getTask(id); }
    updateTask(...args: any[]): Promise<any> { return (this.actor as any).updateTask(...args); }
    deleteTask(id: string): Promise<any> { return (this.actor as any).deleteTask(id); }
    createDocument(...args: any[]): Promise<any> { return (this.actor as any).createDocument(...args); }
    getDocuments(): Promise<any> { return (this.actor as any).getDocuments(); }
    getDocumentsByProject(projectId: string): Promise<any> { return (this.actor as any).getDocumentsByProject(projectId); }
    getDocument(id: string): Promise<any> { return (this.actor as any).getDocument(id); }
    updateDocument(...args: any[]): Promise<any> { return (this.actor as any).updateDocument(...args); }
    deleteDocument(id: string): Promise<any> { return (this.actor as any).deleteDocument(id); }
    getMyNotifications(): Promise<any> { return (this.actor as any).getMyNotifications(); }
    markNotificationRead(id: string): Promise<any> { return (this.actor as any).markNotificationRead(id); }
    markAllNotificationsRead(): Promise<any> { return (this.actor as any).markAllNotificationsRead(); }
    addComment(...args: any[]): Promise<any> { return (this.actor as any).addComment(...args); }
    getComments(entityId: string): Promise<any> { return (this.actor as any).getComments(entityId); }
    deleteComment(id: string): Promise<any> { return (this.actor as any).deleteComment(id); }
    getRecentActivity(limit: bigint): Promise<any> { return (this.actor as any).getRecentActivity(limit); }
    getDashboardStats(): Promise<any> { return (this.actor as any).getDashboardStats(); }
    registerProfile(...args: any[]): Promise<any> { return (this.actor as any).registerProfile(...args); }
    getMyProfile(): Promise<any> { return (this.actor as any).getMyProfile(); }
    getAllProfiles(): Promise<any> { return (this.actor as any).getAllProfiles(); }
    getProfile(principal: any): Promise<any> { return (this.actor as any).getProfile(principal); }
    updateProfile(...args: any[]): Promise<any> { return (this.actor as any).updateProfile(...args); }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
